language: node_js
os:
- osx

node_js: 14

git:
  depth: 3

before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then
    export DISPLAY=':99.0'
    /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  fi

install:
  - npm install

script:
  - npm test

after_success: npm run coveralls